name: 02. checkout 실습
on:
  workflow_dispatch

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 전 디렉토리 확인
        run: |
          pwd
          ls -al

      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 체크아웃 후 디렉토리 확인
        run: |
          pwd
          ls -al
