name: 03. secrets 활용
on:
  workflow_dispatch

jobs:
  use-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: secrets 출력 시도
        run: |
          echo "Secret: ${{ secrets.MY_SECRET }}"
        # 로그에 Secret: *** 출력 (마스킹됨)
