name: 04. matrix 실습
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fruits: [Apple, Banana]
        sizes: [Small, Large]
    steps:
      - name: 조합 출력
        run: |
          echo "과일: ${{ matrix.fruits }}"
          echo "크기: ${{ matrix.sizes }}"
