name: 06. Reusable Hello 호출
on:
  workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI 작업 수행"

  call-reusable:
    needs: ci
    uses: ./.github/workflows/06-reusable-hello.yml
    # 주의: runs-on 지정하지 않음 (재사용 워크플로우가 자체 정의)

  after:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - run: echo "Reusable 호출 완료 후 작업"
